# Generated by Django 4.0 on 2021-12-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0004_alter_client_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_lastname',
            field=models.CharField(max_length=10),
        ),
    ]
