# Generated by Django 4.0 on 2021-12-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0005_alter_client_client_lastname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.RenameField(
            model_name='client',
            old_name='client_ftd',
            new_name='client_phone',
        ),
        migrations.AddField(
            model_name='client',
            name='client_email',
            field=models.EmailField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='client_reg_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='client_salesman',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
