# Generated by Django 4.0 on 2021-12-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0007_client_client_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_phone',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
    ]
