# Generated by Django 4.0 on 2021-12-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0009_alter_client_client_salesman'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_retention',
            field=models.CharField(default=2, max_length=5),
            preserve_default=False,
        ),
    ]
