# Generated by Django 4.0 on 2021-12-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name2', models.CharField(max_length=10)),
                ('client_cash', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
