# Generated by Django 4.0 on 2021-12-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operation', '0002_alter_operation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='operation',
            name='operation_status',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
