# Generated by Django 4.0 on 2021-12-16 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Operation', '0003_status_operation_operation_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Status', 'verbose_name_plural': 'Status'},
        ),
    ]
