# Generated by Django 4.0 on 2021-12-16 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Operation', '0004_alter_status_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='operation_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Operation.status'),
        ),
    ]
