# Generated by Django 4.0 on 2021-12-21 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_client_retention_alter_client_salesman'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='Active',
            new_name='active',
        ),
    ]
