# Generated by Django 4.0 on 2021-12-20 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_client_retention_client_salesman'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='who',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crm.employee'),
            preserve_default=False,
        ),
    ]
