# Generated by Django 4.0 on 2021-12-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_rename_active_bank_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='reg_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
