# Generated by Django 4.0 on 2021-12-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_employee_reg_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='type',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
