# Generated by Django 4.0 on 2021-12-21 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_operation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='crm.client'),
        ),
    ]
