# Generated by Django 4.0 on 2021-12-22 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_operation_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='operacje',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transakcje', to='crm.operation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operation',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.status'),
        ),
    ]
