# Generated by Django 4.0 on 2021-12-22 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_client_operacje_alter_operation_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='operacje',
            new_name='ftd_trans',
        ),
    ]
