# Generated by Django 4.0 on 2021-12-20 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_operation_who'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='bank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bank', to='crm.bank'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operation',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stat', to='crm.status'),
            preserve_default=False,
        ),
    ]
