# Generated by Django 4.0 on 2021-12-20 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_alter_operation_bank_alter_operation_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='status',
            new_name='Active',
        ),
    ]
