# Generated by Django 4.0 on 2021-12-22 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_rename_operacje_client_ftd_trans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='ftd_trans',
        ),
        migrations.AddField(
            model_name='client',
            name='client_cash',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clientcash', to='crm.operation'),
            preserve_default=False,
        ),
    ]
